
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 24 12:38:50 EST 2017
//----------------------------------------------------

package fractal.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PENDOWN = 35;
  public static final int LPAREN = 12;
  public static final int REPEAT = 3;
  public static final int INT = 36;
  public static final int RENDER = 4;
  public static final int FORWARD = 32;
  public static final int MINUS = 20;
  public static final int RPAREN = 13;
  public static final int NOT = 27;
  public static final int AND = 28;
  public static final int LT = 24;
  public static final int OR = 29;
  public static final int COMMA = 14;
  public static final int DIV = 22;
  public static final int PLUS = 19;
  public static final int ID = 38;
  public static final int FRACTAL = 2;
  public static final int LEFT = 30;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int HOME = 8;
  public static final int MOD = 23;
  public static final int EQ = 26;
  public static final int REAL = 37;
  public static final int COLON = 10;
  public static final int LBRACE = 15;
  public static final int COMPOSE = 17;
  public static final int SAVE = 6;
  public static final int CLEAR = 9;
  public static final int RBRACE = 16;
  public static final int PENUP = 34;
  public static final int END = 11;
  public static final int DEF = 5;
  public static final int SEQUENCE = 18;
  public static final int BACK = 33;
  public static final int RIGHT = 31;
  public static final int RESTORE = 7;
  public static final int GT = 25;
}

