
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 06 10:27:09 EST 2017
//----------------------------------------------------

package fractal.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PENDOWN = 36;
  public static final int LPAREN = 10;
  public static final int REPEAT = 3;
  public static final int INT = 37;
  public static final int RENDER = 4;
  public static final int FORWARD = 31;
  public static final int MINUS = 19;
  public static final int RPAREN = 11;
  public static final int NOT = 26;
  public static final int AND = 27;
  public static final int LT = 23;
  public static final int OR = 28;
  public static final int COMMA = 12;
  public static final int DIV = 21;
  public static final int PLUS = 18;
  public static final int ID = 39;
  public static final int FRACTAL = 2;
  public static final int LEFT = 29;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SELF = 9;
  public static final int MUL = 20;
  public static final int HOME = 33;
  public static final int MOD = 22;
  public static final int EQ = 25;
  public static final int REAL = 38;
  public static final int COLON = 15;
  public static final int LBRACE = 13;
  public static final int COMPOSE = 16;
  public static final int SAVE = 6;
  public static final int CLEAR = 34;
  public static final int RBRACE = 14;
  public static final int PENUP = 35;
  public static final int END = 8;
  public static final int DEF = 5;
  public static final int SEQUENCE = 17;
  public static final int BACK = 32;
  public static final int RIGHT = 30;
  public static final int RESTORE = 7;
  public static final int GT = 24;
}

